export const PRODUCTS = [
  {
    id: 1,
    name: "Vanguard Elite",
    original_price: 149,
    discounted_price: 99,
    category_name: "kid",
    is_stock: false,
    rating: 4.3,
    reviews: 109,
    description:
      "These premium leather sneakers embody urban sophistication with their sleek design, high-quality craftsmanship, and attention to detail.",
    trending: true,
    size: 5,
    img: "/assets/images/products-images/image-kids-1.png",
  },

  {
    id: 2,
    name: "Nova Pro X",
    original_price: 130,
    discounted_price: 99,
    category_name: "kid",
    is_stock: true,
    rating: 4.1,
    reviews: 129,
    description:
      "These urban high-top sneakers feature a contemporary silhouette, luxurious materials, and impeccable stitching, making them a stylish choice for fashion-forward individuals.",
    trending: true,
    size: 7,
    img: "/assets/images/products-images/image-kids-2.png",
  },
  {
    id: 3,
    name: "Velocity Prime",
    original_price: 299,
    discounted_price: 199,
    category_name: "kid",
    is_stock: true,
    rating: 3.3,
    reviews: 130,
    description:
      "Made from supple, premium leather, these loafers exude elegance with their minimalist urban aesthetic and effortless slip-on design.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/image-kids-4.png",
  },
  {
    id: 4,
    name: "Equinox Maxima",
    original_price: 399,
    discounted_price: 299,
    category_name: "kid",
    is_stock: true,
    rating: 4.5,
    reviews: 109,
    description:
      "These urban boots are crafted from luxurious suede and boast a modern silhouette, making them a versatile and stylish choice for any occasion.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/image-kids-5.png",
  },
  {
    id: 5,
    name: "Precision Optima",
    original_price: 99,
    discounted_price: 89,
    category_name: "kid",
    is_stock: true,
    rating: 3.4,
    reviews: 39,
    description:
      "Designed for the fashion-conscious urbanite, these sneakers feature bold colors, unique patterns, and premium materials, adding an eye-catching element to any outfit.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/image-kids-6.png",
  },
  {
    id: 6,
    name: "Apex Fusion X",
    original_price: 399,
    discounted_price: 299,
    category_name: "kid",
    is_stock: true,
    rating: 3.6,
    reviews: 32,
    description:
      "These premium leather Chelsea boots offer a perfect blend of urban style and timeless elegance, with their sleek silhouette and comfortable fit.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/image-kids-7.png",
  },
  {
    id: 7,
    name: "Quantum Impact",
    original_price: 599,
    discounted_price: 499,
    category_name: "kid",
    is_stock: true,
    rating: 4.6,
    reviews: 1094,
    description:
      "These urban slip-on sneakers combine fashion-forward design with premium materials, allowing for effortless style and comfort.",
    trending: true,
    size: 7,
    img: "/assets/images/products-images/image-kids-8.png",
  },
  {
    id: 8,
    name: "Elevation Ultra",
    original_price: 699,
    discounted_price: 599,
    category_name: "kid",
    is_stock: true,
    rating: 4.5,
    reviews: 166,
    description:
      "Urban Desert Boots: Made from high-quality materials, these desert boots feature a rugged yet refined urban look, making them an ideal choice for the modern adventurer.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/image-kids-9.png",
  },
  {
    id: 9,
    name: "Radiant Elite",
    original_price: 899,
    discounted_price: 799,
    category_name: "kid",
    is_stock: true,
    rating: 4.6,
    reviews: 47,
    description:
      "These urban leather sandals embody simplicity and sophistication, with their clean lines, premium materials, and understated elegance.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/image-kids-10.png",
  },
  {
    id: 10,
    name: "Ignite Pro X",
    original_price: 399,
    discounted_price: 299,
    category_name: "kid",
    is_stock: true,
    rating: 3.3,
    reviews: 200,
    description:
      "These premium Oxford shoes feature a modern twist on a classic design, with urban-inspired details and impeccable craftsmanship.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/image-kids-11.png",
  },

  {
    id: 11,
    name: "Ascend TechFit",
    original_price: 199,
    discounted_price: 79,
    category_name: "kid",
    is_stock: true,
    rating: 2.7,
    reviews: 19,
    description:
      "Combining cutting-edge technology with urban style, these running shoes feature advanced cushioning, breathable mesh, and a sleek, streamlined design.",
    trending: false,
    size: 4,
    img: "/assets/images/products-images/image-kids-3.png",
  },
];
